name: Build and Deploy Code
on: [push, pull_request]

jobs:
  job1:
    runs-on: ubuntu-latest
    env:
      PYTHONUNBUFFERED: 1
      DATABASE_HOSTNAME: 127.0.0.1
      DATABASE_PORT: 5432
      DATABASE_USERNAME: postgres
      DATABASE_NAME: fastapi
      DATABASE_PASSWORD: adminpassword
      ALGORITHM: HS256
      SECRET_KEY: testing_secret_key_9d25e094faa6ca2556c818166b7a9563b
      ACCESS_TOKEN_EXPIRE_MINUTES: 30

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: adminpassword
          POSTGRES_DB: fastapi
          POSTGRES_HOST_AUTH_METHOD: trust
        ports:
          - '5432:5432'

    steps:
      - name: pulling git repo
        uses: actions/checkout@v4

      
      - name: Clear Committed Local Env Cache
        run: |
          rm -f .env
          rm -f app/.env
          rm -f tests/.env

      - name: install python version 
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: install all dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest httpx pydantic-settings

     

      - name: test with pytest
        env:
          PGHOST: 127.0.0.1
          PGUSER: postgres
          PGPASSWORD: adminpassword
          PGDATABASE: fastapi
        run: python -m pytest tests/ -vv -s










